app = "bot-trading-diamante-v1"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:22"  # Actualizado a la versi√≥n 22

[processes]
  # Cambiamos main.py por bot_diamante_pro.py para activar tu estrategia avanzada
  worker = "python bot_diamante_pro.py" 
